[tools]
"node" = { version = "22.18.0" }
"rust" = { version = "1.88.0", targets = "wasm32-unknown-unknown" }
"ubi:rustwasm/wasm-bindgen" = { version = "0.2.100", extract_all = "true" }
"ubi:WebAssembly/binaryen" = { version = "version_123", extract_all = "true", bin_path = "bin" }
