name: CI

on:
  pull_request:
  push:
  schedule:
  - cron: '00 01 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['20.x', '22.x']

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - run: rustup target add wasm32-unknown-unknown
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
